@host= http://localhost:8080
@hostId=dasd
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOTM4YWJhOS0wMDAzLTQwNDgtODQwZS0wNmQ0MTAxODlkYjciLCJnaXZlbl9uYW1lIjpbIkFtaWNoYWkiLCJNYW50aWJhbmQiXSwianRpIjoiYmZlMmMzYTEtZDBjNC00MzdmLWFhMTgtNDk1ZTUzZjU5OTdhIiwiZXhwIjoxNzI3OTI4NjU4LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.HvBgS965-7duj4PLOlOlLGmQxFQJg5rdy4XDI9NF_uA
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Calamari",
                    "description": "Fried squid"
                }
            ]
        }
    ]
}