@host= http://localhost:5107
GET {{host}}/dinner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MzJiMjFjOC1jYjg1LTQ2YjUtOWNjNi1mMDdjZmFjOTQ1ZWQiLCJnaXZlbl9uYW1lIjpbIkFtaWNoYWkiLCJNYW50aWJhbmQiXSwianRpIjoiYzRlYzIyZmEtY2I0Zi00OWI2LTkwN2QtNWNhM2QxZDNlZjIwIiwiZXhwIjoxNzI3NzAyNTcyLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.6k5AAtet5N0YRr_s-yCYliNyb_ykk5kFwZBd8yzH3UY