@host= http://localhost:8080
GET {{host}}/dinner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlODE3NzM4NC0xMjU3LTQxY2UtODI0Yy0zMDQwM2NiZDYxYTciLCJnaXZlbl9uYW1lIjpbIkFtaWNoYWkiLCJNYW50aWJhbmQiXSwianRpIjoiZTk3YzMwMWYtMmRkZi00ZWVlLWFhNjUtMmZlMDBiYmJhNzBiIiwiZXhwIjoxNzI3NzA1OTY2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.GoNy4bwkJU3flQQS6QTLxetEYAg-kTuMtsd0NDR_bt0